import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

import { H1, H2, Body } from "../components/typography";
import Button from "../components/button";

export default function _404() {
  return (
    <>
      <Head>
        <title>404 Page Not Found- Chiipoultry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_mini.svg" />
      </Head>
      <section className="flex h-[736px] flex-col items-center justify-center">
        <H1>404</H1>
        <H2 className="mb-32">Page Not Found</H2>
        <Body className="mb-16">
          <b>You can checkout:</b>
        </Body>
        <ul className="mb-24 flex items-center gap-32">
          <Link href="/" className="text-attention">
            <li>Home</li>
          </Link>
          <Link href="/about-us" className="text-attention">
            <li>About Us</li>
          </Link>
          <Link href="/" className="text-attention">
            <li>Contact Us</li>
          </Link>
        </ul>
        <Link href="/">
          <Button>
            Shop <Image src="/cart.svg" alt="cart" height={16} width={16} />
          </Button>
        </Link>
      </section>
    </>
  );
}
