import Head from "next/head";

import { H2, Body } from "../components/typography";

export default function aboutUs() {
  return (
    <>
      <Head>
        <title>About Us - Chiipoultry</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo_mini.svg" />
      </Head>
      <section className="flex flex-col items-center px-16 pt-64">
        <H2 className="mt-64 mb-32">About Us</H2>

        <div
          id="text-container"
          className="mb-64 flex max-w-[480px] flex-col gap-24 min-[480px]:text-justify"
        >
          <Body className="mb-16">
            <span className="font-semibold">Chiipoultry</span> is a company
            dedicated to providing poultry farmers with quality equipment. A
            relatively new company with big dreams.
          </Body>
          <Body className="mb-16">
            We not only look to deliver quality products but also resources to
            <span className="font-semibold">
              aid poultry farmers in their businesses.
            </span>{" "}
            We recognise that poultry can be a challenging endeavour, so we aim
            to make your life easier.
          </Body>
          <Body className="mb-16">
            <span className="font-semibold">Chiipoultry Online Store,</span> the
            online store will help all poultry acquire the equipment they desire
            with the ease of a few clicks.
          </Body>
          <Body className="mb-16">
            <span className="font-semibold">Chiipoultry Articles,</span> this
            resource is coming soon. Articles are written by poultry farmers,{" "}
            <span className="font-semibold">for poultry farmers.</span> The
            articles are written to aid potential & current poultry farmers, no
            matter the level & years of experience you might have.
          </Body>
          <Body>
            Stick around for a while, some of the things that are coming are the{" "}
            <span className="font-semibold">
              Chiipoultry Chicken Time Table Generator.
            </span>{" "}
            This will automatically generate a timetable for your specific batch
            that arrived on a specific date. This is one of the unnecessary
            overheads that could be automated, & we plan to make this resource
            free for all poultry farmers.
          </Body>
        </div>
      </section>
    </>
  );
}
